import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cutting Edge Electronics Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <Link href="/" passHref>Home</Link>
          <Link href="/cart" passHref>Cart</Link>
          <Link href="/about-us" passHref>About Us</Link>
        </nav>
      </header>
      <main className={styles.main}>
       
      </main>
    </>
  )
}
