import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useEffect, useState } from "react";
import axios from "axios";
const inter = Inter({ subsets: ["latin"] });
interface Rating {
  rate: number;
  count: number;
}
interface Product {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: Rating;
}
interface Products {
  data: Product[];
}

export default function Home({ data }: Products) {
  return (
    <>
      <Head>
        <title>Cutting Edge Electronics Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <Link href="/" passHref>
            Home
          </Link>
          <Link href="/cart" passHref>
            Cart
          </Link>
          <Link href="/about-us" passHref>
            About Us
          </Link>
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((product) => {
          const {
            id,
            title,
            price,
            description,
            category,
            image,
            rating: { rate, count },
          } = product;
          return (
            <Link
              href={{
                pathname: `/products/${product.id}`,
                query: {
                  id,
                  title,
                  price,
                  description,
                  category,
                  image,
                  rate,
                  count,
                },
              }}
              as={`/products/${product.id}`}
              key={product.id}
              passHref
            >
              <h2>{product.title}</h2>
              <Image
                width={300}
                height={300}
                src={product.image}
                alt={product.title}
              />
            </Link>
          );
        })}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { data } = await axios.get(
    "https://fakestoreapi.com/products/category/electronics"
  );
  return {
    props: {
      data: data,
    },
  };
}
